language: node_js
node_js: lts/*
os: osx
osx_image: xcode10.2
before_install:
  - brew update
install:
  - yarn
before_script:
  - yarn build
  - npm link
script:
  - cit --version
before_deploy:
  - git stash --all
  - yarn
  - yarn build
deploy:
  provider: npm
  email: shamofu@gmail.com
  api_key:
    secure: ZN/1eyNVv6WnOhkfReUZyG//8WFu2du5BKTsAyMEWps9TKYzqLfhEgvUa5YgvVw70qU6s/6l+yjgHa94FxwgZoI6xKZ9HkRIeiU/NYPZYNa7IhyoYurM8pWyC2++IG217X4PsCbv6VnkjLERbvHLflfVSUa+G5XOvrx6LTH1HHCv62Ysut8R7fid7m/yNI7ch/KSWqagpTNTjX6ACy6SI2ECrDP93+q8RMppGlWFOvGEbEVFTwmvN8+dt06V/S7g9KYMSW1HMmvh3z2WVGvwDJhPwrxpeOKUWMZIAu944XCzn+ox+CZS1/4GXRk4G97XmILch7WSewf7Y2JTHpbH5GpdGaLq15xqbaWT1CjTTmHPCncbNVS1sZI1E+WFMMsO8Jn9ZW+lDG0EeKIARpoMNkbtNo8JR0dVzAr79ewbatoFOln2+nC2jWnT25v303gklklIQPrguMLlPpv2ULabYYsPZNcooT7ZKdsMTSzkDCcgsfOe4+XFCS87drKh1y7vuVJfxmJyd77FJBG8CvISE2RWZ9zMjDoQGdt9R0RN4piFmPpBnJBW5/FnS5EQbbBsynD1g9SppYMvg54gh8KtgByHukpa092X0gO6NnvRdA/Cd4d6rILxksSOBi2faACO8nIbC9H7J+RBK0ekCo/lw6p3DwrQ67dNGICBVYXB8Dg=
  skip_cleanup: true
  on:
    tags: true
    repo: shamofu/cit
    branch: master
