language: node_js
node_js: lts/*
os: osx
osx_image: xcode10.1
before_install:
  - brew update
install:
  - yarn
before_script:
  - yarn build
  - npm link
script:
  - cit --version
before_deploy:
  - git stash --all
  - yarn
  - yarn build
deploy:
  provider: npm
  email: shamofu@gmail.com
  api_key:
    secure: epVrNx1P1+TmLdK0L1hXQNsmR3E5/zCzNtFibPn3OWxABk6NEZP7af9AxKEZOW7BrmzjA7HaBRQLrlR5vJYu07v6dGW+JaLP61wYyPSeYQ+zGm1SdWghZsPR/T8DAJjzxcMI+hYuY2VEFT9aI+LfFV5KKdww6el/M3G/P5TmVywS5vaAkVVOyWHuusCGoluNSsI3BltwgMJvXqDyV5xpoTSO5QEhs8U4P5AhSGsQAwuSf4vj0dlTGVrzVCqoC0W4yMLGFZrp9b6orgRbs+3Dr1lmEDpZzqW7GjM/QnbIckSGTEiGfCrAw/6mNNJYlEaEHv9MuO1ZqCNudbAjgEhhdjIVN64sf8bTahFcoEbpChH0YzTYBuHSSDCabbuwfnoggqb88e8x5eSmkmB43DJRJm4AjbFfo1O+g/LzDUELxk8bFpIyEL/vzsGIqgx4fMqg1tuywmJWcFNFLH4N0VpNmVBmeXpI0DRXr3Cu4/aqsXYSrjgchEh3OoGjs1g6sxDVTjIW+IcJlVOEvLkCF/kb1JeD+Tnj8qNyYzo/5UbWLMI6RPQkBYhExFenqfdTQAp97IQ8N+6ZsJ3TVxG12/R/k8fKA3r6HVnWP1lbZM6CnTyUJmgwc5nEzM4LJMzbtssfHPYZ51QBgGrZ0rvXNnHZmfefeQCXXK82xgxqc8PxoiI=
  skip_cleanup: true
  on:
    tags: true
    repo: shamofu/cit
    branch: master
